version: '3.8'

services:
  pixiv_web:
    build: .
    container_name: pixiv_web_app

    ports:
      - "5000:5000"
    volumes:
      - ./pixiv_media.db:/pixiv_media.db
      - ./downloads:/downloads

    restart: always

    command: python run.py